export const ptSpellsName = [
  'Seta Ácida',
  'Espirro Ácido',
  'Ajudar',
  'Alarme',
  'Alterar Auto',
  'Amizade Animal',
  'Mensageiro Animal',
  'Formas Animais',
  'Animar Mortos',
  'Animar Objetos',
  'Casca Antivida',
  'Campo Antimagia',
  'Antipatia/Simetria',
  'Olho Arcano',
  'Mão Arcana',
  'Trava Arcana',
  'Espada Arcana',
  'Aura Mágica do Arcanista',
  'Projeção Astral',
  'Augúrio',
  'Despertar',
  'Flagelo',
  'Banimento',
  'Pele de Árvore',
  'Facho de Esperança',
  'Amaldiçoar',
  'Tentáculos Negros',
  'Barreira de Lâminas',
  'Benção',
  'Míldio',
  'Cegueira/Surdez',
  'Transmutar',
  'Desfoque',
  'Marca de Brando',
  'Mãos Flamejantes',
  'Chamar Relâmpago',
  'Emoções Calmas',
  'Relâmpago em Cadeia',
  'Persuadir Pessoa',
  'Toque Gélido',
  'Círculo da Morte',
  'Clarividência',
  'Clonagem',
  'Névoa Mortal',
  'Spray de Cores',
  'Comando',
  'Comunhão',
  'Comunhão com a Natureza',
  'Compreensão de Idiomas',
  'Compulsão',
  'Cone de Frio',
  'Confusão',
  'Conjurar Animais',
  'Conjurar Celestial',
  'Conjurar Elemental',
  'Conjurar Fada',
  'Conjurar Elementais Menores',
  'Conjurar Seres da Floresta',
  'Contato Plano Superior',
  'Contágio',
  'Contingência',
  'Chama Continua',
  'Controlar Água',
  'Controlar Clima',
  'Anular Magia',
  'Criar Comida e Água',
  'Criar ou Destruir Água',
  'Criar Morto-Vivo',
  'Criação',
  'Cura de Ferimentos',
  'Luzes Dançantes',
  'Escuridão',
  'Visão no Escuro',
  'Luz do Dia',
  'Proteção contra Morte',
  'Explosão Retardada de Bola de Fogo',
  'Meio Plano',
  'Detectar Bem e Mal',
  'Detectar Magia',
  'Detectar Veneno e Doença',
  'Detectar Pensamentos',
  'Portal Dimensional',
  'Disfarçar-se',
  'Desintegrar',
  'Anular Bem e Mal',
  'Anular Magia',
  'Divinação',
  'Favor Divino',
  'Palavra Divina',
  'Domínio de Feras',
  'Domínio de Monstros',
  'Domínio de Pessoa',
  'Sonhar',
  'Ofício de Druida',
  'Terremoto',
  'Rajada Eltrítica',
  'Aprimorar Habilidade',
  'Aumentar/Reduzir',
  'Embaraçar',
  'Enfeitiçar',
  'Eteralidade',
  'Retiro Ligeiro',
  'Olho Mal',
  'Fabricar',
  'Fogo Feérico',
  'Cão Fiel',
  'Vida Falsa',
  'Medo',
  'Queda de Pena',
  'Mente Fraca',
  'Encontrar Familiar',
  'Encontrar Montaria',
  'Encontrar o Caminho',
  'Encontrar Armadilhas',
  'Toque da Morte',
  'Raio de Fogo',
  'Escudo de Fogo',
  'Tempestade de Fogo',
  'Bola de Fogo',
  'Lâmina Chamejante',
  'Golpe de Chama',
  'Esfera Flamejante',
  'Carne para Pedra',
  'Disco Flutuante',
  'Voo',
  'Névoa',
  'Proibição',
  'Gaiola Forçada',
  'Previdência',
  'Liberdade de Movimento',
  'Esfera Gélida',
  'Forma Gasosa',
  'Portal',
  'Geas',
  'Repose Descansado',
  'Inseto Gigante',
  'Glibness',
  'Globo de Invulnerabilidade',
  'Glifo de Guardar',
  'Amora',
  'Untar',
  'Invisibilidade Maior',
  'Restauração Maior',
  'Guardião da Fé',
  'Guardas e Guardiões',
  'Orientação',
  'Raio Guiador',
  'Rajada de Vento',
  'Consagração',
  'Terreno Alucinatório',
  'Dano',
  'Pressa',
  'Cura',
  'Palavra Curativa',
  'Aquecer Metal',
  'Represália Infernal',
  'Banquete dos Heróis',
  'Heroísmo',
  'Risada Horrenda',
  'Prender Monstro',
  'Prender Pessoa',
  'Aura Sagrada',
  'Marca do Caçador',
  'Padrão Hipnótico',
  'Tempestade de Gelo',
  'Identificação',
  'Script Ilusório',
  'Prisão',
  'Nuvem Incendiária',
  'Causar Ferimentos',
  'Praga de Insetos',
  'Chamado Instantâneo',
  'Invisibilidade',
  'Dança Irresistível',
  'Saltar',
  'Arrombar',
  'Lenda e Lore',
  'Restauração Menor',
  'Levitar',
  'Luz',
  'Raio de Trovão',
  'Localizar Animais ou Plantas',
  'Localizar Criatura',
  'Localizar Objeto',
  'Andar Longo',
  'Armadura de Mago',
  'Mão Mágica',
  'Círculo Mágico',
  'Jarro Mágico',
  'Míssil Mágico',
  'Boca Mágica',
  'Arma Mágica',
  'Mansão Magnífica',
  'Imagem Maior',
  'Cura em Massa',
  'Cura em Massa',
  'Palavra Curativa em Massa',
  'Sugestão em Massa',
  'Labirinto',
  'Fundir-se na Pedra',
  'Consertar',
  'Mensagem',
  'Chuva de Meteoros',
  'Mente em Branco',
  'Ilusão Menor',
  'Arco-Íris Ilusório',
  'Imagem Espelhada',
  'Desorientar',
  'Passo Nebuloso',
  'Modificar Memória',
  'Raio de Lua',
  'Mover Terra',
  'Nondetecção',
  'Passar sem Traço',
  'Passagem',
  'Assassino Fantasmagórico',
  'Cavalo Fantasma',
  'Aliado Plano',
  'Ligação Plana',
  'Deslocamento Plano',
  'Crescimento de Plantas',
  'Spray de Veneno',
  'Polimorfo',
  'Palavra do Poder Matar',
  'Palavra do Poder Atordoar',
  'Oração de Cura',
  'Prestidigitação',
  'Spray Prismático',
  'Muralha Prismática',
  'Santuário Privado',
  'Produzir Chama',
  'Ilusão Programada',
  'Imagem de Projeto',
  'Proteção contra Energia',
  'Proteção contra o Mal e o Bem',
  'Proteção contra Veneno',
  'Purificar Alimentos e Bebidas',
  'Ressuscitar',
  'Raio de Fraqueza',
  'Raio de Gelo',
  'Regenerar',
  'Reencarnar',
  'Remover Maldição',
  'Esfera Rígida',
  'Resistência',
  'Ressurreição',
  'Gravidade Reversa',
  'Reviver',
  'Truque de Corda',
  'Chama Sagrada',
  'Santuário',
  'Raio Abrasador',
  'Espionar',
  'Baú Secreto',
  'Ver Invisibilidade',
  'Ilusão',
  'Enviar',
  'Ocultar',
  'Metamorfose',
  'Estilhaçar',
  'Escudo',
  'Escudo da Fé',
  'Cajado Encantado',
  'Toque Chocante',
  'Silêncio',
  'Imagem Silenciosa',
  'Simulacro',
  'Sono',
  'Tempestade de Granizo',
  'Lentidão',
  'Poupando o Moribundo',
  'Falar com Animais',
  'Falar com Mortos',
  'Falar com Plantas',
  'Escalada de Aranha',
  'Crescimento de Espinhos',
  'Guardiões Espirituais',
  'Arma Espiritual',
  'Névoa Fedorenta',
  'Moldar Pedra',
  'Pele de Pedra',
  'Tempestade da Vingança',
  'Sugestão',
  'Raio de Sol',
  'Explosão Solar',
  'Símbolo',
  'Telecinese',
  'Ligação Telepática',
  'Teleporte',
  'Círculo de Teleporte',
  'Tamatúrgia',
  'Onda de Choque',
  'Parar o Tempo',
  'Cabana Pequenina',
  'Línguas',
  'Transporte por Plantas',
  'Passos da Árvore',
  'Transformação Verdadeira',
  'Ressurreição Verdadeira',
  'Verdadeira Visão',
  'Golpe Certeiro',
  'Servo Invisível',
  'Toque Vampírico',
  'Zombaria Viciosa',
  'Muralha de Fogo',
  'Muralha de Força',
  'Muralha de Gelo',
  'Muralha de Pedra',
  'Muralha de Espinhos',
  'Laço Protetor',
  'Respiração Aquática',
  'Caminhar sobre a Água',
  'Teia',
  'Estranho',
  'Caminho do Vento',
  'Barreira de Vento',
  'Desejo',
  'Palavra de Regresso',
  'Zona da Verdade',
];
