export enum Language {
  COMMON = 'Common',
  ELVISH = 'Elvish',
  DWARVISH = 'Dwarvish',
  HALFLING = 'Halfling',
  DRACONIC = 'Draconic',
  GIANT = 'Giant',
  GNOMISH = 'Gnomish',
  GOBLIN = 'Goblin',
  ORC = 'Orc',
  ABYSSAL = 'Abyssal',
  CELESTIAL = 'Celestial',
  INFERNAL = 'Infernal',
  PRIMORDIAL = 'Primordial',
  SYLVAN = 'Sylvan',
  UNDERCOMMON = 'Undercommon',
  OTHER = 'Other',
}
