export enum CharacterRaces {
  DWARF = 'Dwarf',
  ELF = 'Elf',
  HALFLING = 'Halfling',
  HUMAN = 'Human',
  DRAGONBORN = 'Dragonborn',
  GNOME = 'Gnome',
  HALF_ELF = 'Half-Elf',
  HALF_ORC = 'Half-Orc',
  TIEFLING = 'Tiefling',
  AASIMAR = 'Aasimar',
  FIRBOLG = 'Firbolg',
  GENASI = 'Genasi',
  GOLIATH = 'Goliath',
  KENKU = 'Kenku',
  LIZARDFOLK = 'Lizardfolk',
  TABAXI = 'Tabaxi',
  TRITON = 'Triton',
  BUGBEAR = 'Bugbear',
  GOBLIN = 'Goblin',
  HOBGOBLIN = 'Hobgoblin',
  KOBOLD = 'Kobold',
  ORC = 'Orc',
  YUAN_TI_PUREBLOOD = 'Yuan-Ti Pureblood',
}

export enum MonsterRaces {
  ABERRATION = 'Aberration',
  BEAST = 'Beast',
  CELESTIAL = 'Celestial',
  CONSTRUCT = 'Construct',
  DRAGON = 'Dragon',
  ELEMENTAL = 'Elemental',
  FEY = 'Fey',
  FIEND = 'Fiend',
  GIANT = 'Giant',
  HUMANOID = 'Humanoid',
  MONSTROSITY = 'Monstrosity',
  OOZE = 'Ooze',
  PLANT = 'Plant',
  UNDEAD = 'Undead',
}
